[package]
name = "divisibility"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"  # num-traits is needed as it is a common dependency for num-bigint and num-integer


